=== seerdata/json-schema-test/test/schemas/customer_schema_1.json
{ "$schema" : "http://json-schema.org/draft-04/schema#"
, "type" : "object"
, "properties" :
{

"access_token" : {
  "type" : "string",
  "required" : true
},
"dimension" : {
  "type" : "string",
  "required" : true
},
"key" : {
  "type" : "string",
  "required" : true
},
"value" : {
  "type" : "integer",
  "required" : true
},
"created_at" : {
  "type" : "string",
  "required" : true
},
"interval" :
    { "type" : "array",
      "required" : true
    , "items" :
      { "anyOf" :
        [ { "type" : "string", "pattern" : "hours"}
        , { "type" : "string", "pattern" : "weeks"}
        , { "type" : "string", "pattern" : "months"}
        ]
      }
    },
"calculation" :
    { "type" : "array",
      "required" : true
    , "items" :
      { "anyOf" :
        [ { "type" : "string", "pattern" : "sum"}
        , { "type" : "string", "pattern" : "count"}
        , { "type" : "string", "pattern" : "average"}
        , { "type" : "string", "pattern" : "standard_deviation"}
        , { "type" : "string", "pattern" : "linear_regression"}
        ]
      }
    }
  }
}

=== seerdata/json-schema-test/test/data/customer_data_1.json
{
  "access_token": "212efc9f-f60e-402a-a326-225872a0b0a8",
  "dimension": "job-skills",
  "key": "java",
  "value": 8,
  "created_at": "2014-08-06 17:51:10 +0000",
  "interval": [
    "hours",
    "weeks",
    "months"
  ],
  "calculation": [
    "count",
    "sum",
    "average",
    "standard_deviation",
    "linear_regression"
  ]
}
